---

- name: Get unseal key
  shell: "grep 'Unseal Key' /tmp/vault_output  | sed -e 's/^.*: //'"
  register: unseal_output
  always_run: yes

- name: Get root token
  shell: "grep 'Root Token' /tmp/vault_output  | sed -e 's/^.*: //'"
  register: token_output
  always_run: yes

- name: Set facts
  set_fact:
    vault_token: "{{ token_output.stdout }}"
    unseal_key: "{{ unseal_output.stdout }}"
  always_run: yes
